### ISSUE TITLE
can get the point index ?

### ISSUE THREAD

**Issue by zuixiaosanlang** [cdalitz/kdtree-cpp#2]

**Comment by cdalitz** [comment]
Can you please elaborate what you are trying to achieve?

If you are not interested in the point coordinates, but into some label assigned to each node (e.g. an index), you can use the property `data` of  `KdNode`. Note that `k_nearest_neighbors` does not return points, but a `KdNodeVector`, so you can access the `data` attribute of the nodes.

**Comment by zuixiaosanlang** [comment]
thanks for reply me.
yes， i also interested in the label(point index).

i donot know where to change the code 

but i found property data of KdNode is all the same, 

![image](https://user-images.githubusercontent.com/20105627/186299021-24a02a1a-6aec-48ee-9ed8-d00b84017e07.png)

**Comment by zuixiaosanlang** [comment]
@cdalitz 
thank you. i get it

**Comment by cdalitz** [comment]
As I needed this myself, I have added an additional public attribute *index* to `KdNode` in the new release version 1.2.
